title: Work Notes
description: notes and documentation for work
theme: just-the-docs

url: https://ericwu1997.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
